services:
  app:
    build:
      context: .
      dockerfile: DockerfileProd
    container_name: portfolio-ws
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - sqlite-db:/app/data

volumes:
  sqlite-db:
    external: true