services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379

  portfolio-ws:
    build:
      context: .
      dockerfile: DockerfileDev
    container_name: portfolio-ws
    ports:
      - 5010:5010
    env_file:
      - .env.development
    volumes:
      - ./data:/app/data
    depends_on:
      - redis-server
