FROM node:14-alpine

# Create app directory
WORKDIR /portfolio-mailer

# Install app dependencies
COPY package*.json ./
RUN npm install

#To bundle your app’s source code inside the Docker image:
COPY . .

EXPOSE 5000
CMD ["yarn", "start"]