#Build Stage Start
FROM node:14-alpine as builder
WORKDIR /portfolio-mailer
COPY package*.json ./
RUN npm install
COPY . .
RUN yarn build

# Run Stage Start
FROM nginx
COPY --from=builder /portfolio-mailer/build /usr/share/nginx/html