services:
  app:
    image: alexjcm/portfolio-ws
    container_name: portfolio-ws
    restart: always
    ports:
      - 5000:5000
    env_file:
      - ${HOME}/secrets/.env
    volumes:
      - ${HOME}/data:/app/data
    logging:
      driver: 'json-file'
      options:
        max-file: 10
        max-size: 4m
